# twilight requires newer rustc than what is in alpine:latest
FROM alpine:edge AS builder

RUN apk add cargo

# Precache crates.io index
RUN cargo search >/dev/null

WORKDIR /build
COPY proto/ /build/proto
COPY gateway/ /build/gateway

RUN (cd gateway && cargo build --release)

FROM alpine:latest

COPY --from=builder /build/gateway/target/release/pluralkit /opt/gateway

ENTRYPOINT ["/opt/gateway"]
