{
 "title": "PluralKit Stats",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "System Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "systems" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Member Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "members" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxied Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "messages" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Linked Accounts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "accounts" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Database response time (ms)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "database_query",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Database success rate (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "database_query",
     "query": "SELECT mean(\"success\") FROM \"database_query\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Command Invocations",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "command" ], "type": "tag" }
     ],
     "measurement": "command",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "execution_time" ], "type": "alias" }
      ],
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "execution_time" ], "type": "alias" }
      ],
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Webhook executions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Webhook response time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "webhook",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Webhook success rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "webhook",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Command execution time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "command",
     "select": [
      [
       { "params": [ "execution_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Command response time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "command",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}