[package]
name = "migrate"
version = "0.1.0"
edition = "2024"

[dependencies]
libpk = { path = "../libpk" }

anyhow = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
