name: PluralKit CI
on:
  push:
  pull_request:

jobs:
  build_container:
    name: Build CI container
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/pluralkit/ci:${{ github.sha }}
        file: ci/Dockerfile
  spawn_jobs:
    name: Spawn jobs
    runs-on: ubuntu-latest
    needs: ["build_container"]
    container:
      image: ghcr.io/pluralkit/ci:${{ github.sha }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    env:
      DOCKER_HOST: unix:///var/run/docker.sock

      GITHUB_APP_TOKEN: ${{ secrets.COMMIT_STATUS_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      GIT_SHA: ${{ github.sha }}

      REPO_URL: https://github.com/${{ github.repository }}
      OLD_SHA: ${{ github.event.before }}
      IS_FORCE_PUSH: ${{ github.event.forced }}
    steps:
    - run: /spawn_jobs.py
